### ISSUE TITLE
Support dynamic IP

### ISSUE THREAD

**Issue by magicstone1412** [befranz/hshelp#3]
As far as I know, this script only support static IP. 

I'd like to run full node at my home with a dynamic IP on my orange pi board to support the network. Could you please make a script to check IP every 2 minutes ( or like so) and restart hsd with new IP (if it was changed) to accept inbound connections.

Thank you.

**Comment by befranz** [comment]
Your support is very appreciated but even though it's basically possible (additionally to special router settings if your ISP even allows inbound connections), it's bad for the network because your old dynamic address(es) are still known in the network and nodes try to connect to. So I hope you understand for the sake of network sanity (1 such would not be a problem but think about many) I won't support this by a script.
